### ISSUE TITLE
Error while executing query

### ISSUE THREAD

**Issue by syedrafeyiprice** [hsen-dev/vscode-elastic#18]
I am able to connect and run to following ES server using Sense while VsCode ext is giving error 

**getaddrinfo ENOTFOUND https https:80**

https://tx:fGcXoXcAtYaWfUpE@es-qa.tx.com:443

**Comment by hsen-dev** [comment]
#17

**Comment by hsen-dev** [comment]
a2511e0710b6067e743d12b335ee116ba2463d33
