### ISSUE TITLE
Allow ctrl+enter to run command

### ISSUE THREAD

**Issue by rightaway** [hsen-dev/vscode-elastic#26]
To be consistent with kibana's dev tools console and many other programs, ctrl+enter should be able to run the command (instead of or in addition to alt+enter).

**Comment by KenDobbins** [comment]
I have submitted PR for this. I feel the same way :)

https://github.com/hsen-dev/vscode-elastic/pull/28

**Comment by KenDobbins** [comment]
This is now merged and can be closed. :)
