### ISSUE TITLE
Hangs when Executing Query

### ISSUE THREAD

**Issue by dennisfoconnor** [hsen-dev/vscode-elastic#30]
This appears to have happened with the most recent update.

When I try to execute a query, the executing query message appears in the status bar, but it never returns results and no error message ever appears.

I've attempted to use different hosts. I have also tried prefixing the host with `http://`.

I'm using version 1.24.1 of VS Code with version 0.13.1 of the plugin.

**Comment by wangfei-stu** [comment]
+1! I have the same problem now . when i use 'alt + enter' it noticed '**Running the contributed command:'elastic.execute' failed.**' 
ex: version 1.24.1 of VS Code with version 0.13.1 of the plugin.

**Comment by lsyarn** [comment]
version 0.13.2 still have the same problem. There is a temporary solution，put an empty brace under your POST/GET query. For example:
'''
GET _cat/indices/gather-034*
{}
'''
