### ISSUE TITLE
Updating VS Code to 1.37.0 breaks all features

### ISSUE THREAD

**Issue by chenzhuoyu** [hsen-dev/vscode-elastic#45]
* Cannot execute any query
![image](https://user-images.githubusercontent.com/8230799/62767107-81791d80-bac6-11e9-9bfa-cd3ac453c895.png)

* Cannot set ES host
![image](https://user-images.githubusercontent.com/8230799/62767142-981f7480-bac6-11e9-92f9-aabd74cdcb1e.png)

* Cannot "auto-indent"
![image](https://user-images.githubusercontent.com/8230799/62767155-a7062700-bac6-11e9-86ec-619ea7f933c7.png)

* Syntax highlighting looks incorrect
![image](https://user-images.githubusercontent.com/8230799/62767040-61e1f500-bac6-11e9-9a36-2ea89746e6fc.png)

* Operating System:
```
macOS 10.14.6
```

* VS Code:
```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

Uninstall and re-install the plugin does not help.

**Comment by AnthAbou** [comment]
@chenzhuoyu did you manage to resolve this?

**Comment by chenzhuoyu** [comment]
> @chenzhuoyu did you manage to resolve this?

The next day when I opened VS Code, somehow it works again. I really don't know why.... So close this issue fow now.
