### ISSUE TITLE
Parse error when non-json result (e.g. _cat/)

### ISSUE THREAD

**Issue by froberg** [hsen-dev/vscode-elastic#6]
When the setting **elastic.showResultAsDocument** is set to **true** (default), running queries list **_cat** 
 (where result us not JSON format) will cause a parse error when parsing result.  [think it is here](https://github.com/hsen-dev/vscode-elastic/blob/1cb3d45d5b8d2d6d1cc75a38b92fd9cbe0b3c19a/src/extension.ts#L184)

Can be good to support this and also there is no message or other indication that the query didn't succeed.

**Comment by Heatwave** [comment]
It should be able to fixed on: #9 , just catch the parse exception and then show the raw result.

**Comment by hsen-dev** [comment]
thanks @Heatwave for your contribution.
